### ISSUE TITLE
How is departure time generated?

### ISSUE THREAD

**Issue by wen-ye-xwz** [Yasoz/SynthTraj#2]
Hi, thank you for providing the synthetic data generated! For the four attributes [trip distance, trip time, departure time, sample points] (I assume these are descriptions of the synthetic trajectories generated so it should be different from the attributes of original trajectories that are used to generate synthetic ones), I understand that trip distance, trip time, sample points can be calculated from the synthetic trajectory by calculating distance between points and counting the number of points in a trajectory. But I was wondering how departure time is calculated. I was also wondering why trip total time is length of points *3, Thank you!

**Comment by Yasoz** [comment]
The departure time is not calculated. It's an attribute that guides the trajectory synthesis. The trip total time is the length of points *3 since we assume the sample rate is 3s. The reason for this assumption is that most of the original data has a sampling rate of 3 seconds. Therefore, we provide both these types of time information.
